### ISSUE TITLE
Installed Doctype Causes Error Dialog with AutoMapperMappingException

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/content-templates#1]
Umbraco 7.4.3. ContentTemplates 0.2.0. Looks like installing this installs two document types, Content Template and Content Template Folder. When I clicked on one of them (Content Template, I think), I got this error dialog:

![doctype-error-dialog](https://cloud.githubusercontent.com/assets/5933222/19698766/76345b9a-9aa5-11e6-940d-eee99b87b0ef.png)

Here's the raw text from that dialog:

```
An error occured



 Mapping types:
 ContentType -> IEnumerable`1
 Umbraco.Core.Models.ContentType -> System.Collections.Generic.IEnumerable`1[[Umbraco.Web.Models.ContentEditing.PropertyGroupDisplay`1[[Umbraco.Web.Models.ContentEditing.PropertyTypeDisplay, umbraco, Version=1.0.5948.18146, Culture=neutral, PublicKeyToken=null]], umbraco, Version=1.0.5948.18146, Culture=neutral, PublicKeyToken=null]]

 Destination path:
 DocumentTypeDisplay.Groups.Groups

 Source value:
 Umbraco.Core.Models.ContentType

EXCEPTION DETAILS

AutoMapper.AutoMapperMappingException: 

 Mapping types:
 ContentType -> IEnumerable`1
 Umbraco.Core.Models.ContentType -> System.Collections.Generic.IEnumerable`1[[Umbraco.Web.Models.ContentEditing.PropertyGroupDisplay`1[[Umbraco.Web.Models.ContentEditing.PropertyTypeDisplay, umbraco, Version=1.0.5948.18146, Culture=neutral, PublicKeyToken=null]], umbraco, Version=1.0.5948.18146, Culture=neutral, PublicKeyToken=null]]

 Destination path:
 DocumentTypeDisplay.Groups.Groups

 Source value:
 Umbraco.Core.Models.ContentType
STACKTRACE

at Umbraco.Web.Editors.ContentTypeController.GetById(Int32 id)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
INNER EXCEPTION

System.InvalidOperationException: No property editor could be resolved with the alias: RB.DocumentTypePicker, ensure all packages are installed correctly.
at Umbraco.Web.Models.Mapping.PropertyTypeGroupResolver`1.MapProperties(IEnumerable`1 properties, IContentTypeBase contentType, Int32 groupId, Boolean inherited)
   at Umbraco.Web.Models.Mapping.PropertyTypeGroupResolver`1.ResolveCore(IContentTypeComposition source)
   at AutoMapper.ValueResolver`2.Resolve(ResolutionResult source)
   at AutoMapper.PropertyMap.<ResolveValue>b__6(ResolutionResult current, IValueResolver resolver)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.PropertyMap.ResolveValue(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)


```

**Comment by Nicholas-Westby** [comment]
Probably because I didn't have this installed: https://our.umbraco.org/projects/backoffice-extensions/document-type-picker-for-v7/

Might be worth updating the package page on our.umbraco.org to indicate that other package must be installed first.

**Comment by Nicholas-Westby** [comment]
Added some notes about the dependency on the project page here: https://our.umbraco.org/projects/backoffice-extensions/contenttemplates/
